# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integrate"

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  rector:
    name: "Rector"

    runs-on: ubuntu-latest

    container: php:7.4-cli-alpine3.12

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Composer"
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer

      - name: "Determine composer cache directory"
        id: determine-composer-cache-directory
        run: echo ::set-output name=directory::$(composer config cache-dir)

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v2
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}
          restore-keys: php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: "Install locked dependencies from composer.lock"
        run: composer install --prefer-dist  --no-interaction --no-progress --no-scripts

      - name: "Run rector/rector"
        run: vendor/bin/rector process -vvv
